// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, workspace_id, hash, label)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateAPIKeyParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID uuid.UUID   `json:"workspace_id"`
	Hash        []byte      `json:"hash"`
	Label       pgtype.Text `json:"label"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.WorkspaceID,
		arg.Hash,
		arg.Label,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getWorkspaceIDByAPIKeyHash = `-- name: GetWorkspaceIDByAPIKeyHash :one
SELECT workspace_id
FROM api_keys
WHERE hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetWorkspaceIDByAPIKeyHash(ctx context.Context, hash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getWorkspaceIDByAPIKeyHash, hash)
	var workspace_id uuid.UUID
	err := row.Scan(&workspace_id)
	return workspace_id, err
}
