// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (id, workspace_id, name, level)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, level
`

type CreateCollectionParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Level       string    `json:"level"`
}

type CreateCollectionRow struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Level       string    `json:"level"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (CreateCollectionRow, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Level,
	)
	var i CreateCollectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Level,
	)
	return i, err
}

const getCollectionAutoBackfill = `-- name: GetCollectionAutoBackfill :one
SELECT auto_backfill FROM collections WHERE id = $1
`

func (q *Queries) GetCollectionAutoBackfill(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getCollectionAutoBackfill, id)
	var auto_backfill bool
	err := row.Scan(&auto_backfill)
	return auto_backfill, err
}

const getCollectionByName = `-- name: GetCollectionByName :one
SELECT id, workspace_id, name, level, auto_backfill
FROM collections
WHERE workspace_id = $1 AND name = $2
`

type GetCollectionByNameParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
}

type GetCollectionByNameRow struct {
	ID           uuid.UUID `json:"id"`
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	Name         string    `json:"name"`
	Level        string    `json:"level"`
	AutoBackfill bool      `json:"auto_backfill"`
}

func (q *Queries) GetCollectionByName(ctx context.Context, arg GetCollectionByNameParams) (GetCollectionByNameRow, error) {
	row := q.db.QueryRow(ctx, getCollectionByName, arg.WorkspaceID, arg.Name)
	var i GetCollectionByNameRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Level,
		&i.AutoBackfill,
	)
	return i, err
}

const setAutoBackfill = `-- name: SetAutoBackfill :exec
UPDATE collections SET auto_backfill = $3, updated_at = now()
WHERE workspace_id = $1 AND id = $2
`

type SetAutoBackfillParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	ID           uuid.UUID `json:"id"`
	AutoBackfill bool      `json:"auto_backfill"`
}

func (q *Queries) SetAutoBackfill(ctx context.Context, arg SetAutoBackfillParams) error {
	_, err := q.db.Exec(ctx, setAutoBackfill, arg.WorkspaceID, arg.ID, arg.AutoBackfill)
	return err
}
