// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (id, workspace_id, name, level)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, name, level
`

type CreateCollectionParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Level       string    `json:"level"`
}

type CreateCollectionRow struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Level       string    `json:"level"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (CreateCollectionRow, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Level,
	)
	var i CreateCollectionRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Level,
	)
	return i, err
}

const getCollectionByName = `-- name: GetCollectionByName :one
SELECT id, workspace_id, name, level
FROM collections
WHERE workspace_id = $1 AND name = $2
`

type GetCollectionByNameParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
}

type GetCollectionByNameRow struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Level       string    `json:"level"`
}

func (q *Queries) GetCollectionByName(ctx context.Context, arg GetCollectionByNameParams) (GetCollectionByNameRow, error) {
	row := q.db.QueryRow(ctx, getCollectionByName, arg.WorkspaceID, arg.Name)
	var i GetCollectionByNameRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Level,
	)
	return i, err
}
