// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (id, workspace_id, collection_id, record_id, type, revision, state_after, actor, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type AppendEventParams struct {
	ID             uuid.UUID   `json:"id"`
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	CollectionID   uuid.UUID   `json:"collection_id"`
	RecordID       uuid.UUID   `json:"record_id"`
	Type           string      `json:"type"`
	Revision       int64       `json:"revision"`
	StateAfter     []byte      `json:"state_after"`
	Actor          pgtype.Text `json:"actor"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.Exec(ctx, appendEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.RecordID,
		arg.Type,
		arg.Revision,
		arg.StateAfter,
		arg.Actor,
		arg.IdempotencyKey,
	)
	return err
}

const getReplayEvent = `-- name: GetReplayEvent :one
SELECT record_id, collection_id, revision, state_after, actor, type
FROM events
WHERE workspace_id = $1 AND idempotency_key = $2
ORDER BY seq DESC
LIMIT 1
`

type GetReplayEventParams struct {
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

type GetReplayEventRow struct {
	RecordID     uuid.UUID   `json:"record_id"`
	CollectionID uuid.UUID   `json:"collection_id"`
	Revision     int64       `json:"revision"`
	StateAfter   []byte      `json:"state_after"`
	Actor        pgtype.Text `json:"actor"`
	Type         string      `json:"type"`
}

func (q *Queries) GetReplayEvent(ctx context.Context, arg GetReplayEventParams) (GetReplayEventRow, error) {
	row := q.db.QueryRow(ctx, getReplayEvent, arg.WorkspaceID, arg.IdempotencyKey)
	var i GetReplayEventRow
	err := row.Scan(
		&i.RecordID,
		&i.CollectionID,
		&i.Revision,
		&i.StateAfter,
		&i.Actor,
		&i.Type,
	)
	return i, err
}
