// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (id, workspace_id, collection_id, record_id, type, revision, state_after, actor, idempotency_key, trace)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type AppendEventParams struct {
	ID             uuid.UUID   `json:"id"`
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	CollectionID   uuid.UUID   `json:"collection_id"`
	RecordID       uuid.UUID   `json:"record_id"`
	Type           string      `json:"type"`
	Revision       int64       `json:"revision"`
	StateAfter     []byte      `json:"state_after"`
	Actor          pgtype.Text `json:"actor"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Trace          []byte      `json:"trace"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.Exec(ctx, appendEvent,
		arg.ID,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.RecordID,
		arg.Type,
		arg.Revision,
		arg.StateAfter,
		arg.Actor,
		arg.IdempotencyKey,
		arg.Trace,
	)
	return err
}

const getReplayEvent = `-- name: GetReplayEvent :one
SELECT record_id, collection_id, revision, state_after, actor, type
FROM events
WHERE workspace_id = $1 AND idempotency_key = $2
ORDER BY seq DESC
LIMIT 1
`

type GetReplayEventParams struct {
	WorkspaceID    uuid.UUID   `json:"workspace_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

type GetReplayEventRow struct {
	RecordID     uuid.UUID   `json:"record_id"`
	CollectionID uuid.UUID   `json:"collection_id"`
	Revision     int64       `json:"revision"`
	StateAfter   []byte      `json:"state_after"`
	Actor        pgtype.Text `json:"actor"`
	Type         string      `json:"type"`
}

func (q *Queries) GetReplayEvent(ctx context.Context, arg GetReplayEventParams) (GetReplayEventRow, error) {
	row := q.db.QueryRow(ctx, getReplayEvent, arg.WorkspaceID, arg.IdempotencyKey)
	var i GetReplayEventRow
	err := row.Scan(
		&i.RecordID,
		&i.CollectionID,
		&i.Revision,
		&i.StateAfter,
		&i.Actor,
		&i.Type,
	)
	return i, err
}

const getStateAtEvent = `-- name: GetStateAtEvent :one
SELECT state_after, revision, type
FROM events e
WHERE e.workspace_id = $1 AND e.collection_id = $2 AND e.record_id = $3
  AND e.seq <= (SELECT sub.seq FROM events sub WHERE sub.id = $4)
ORDER BY e.seq DESC
LIMIT 1
`

type GetStateAtEventParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	RecordID     uuid.UUID `json:"record_id"`
	ID           uuid.UUID `json:"id"`
}

type GetStateAtEventRow struct {
	StateAfter []byte `json:"state_after"`
	Revision   int64  `json:"revision"`
	Type       string `json:"type"`
}

func (q *Queries) GetStateAtEvent(ctx context.Context, arg GetStateAtEventParams) (GetStateAtEventRow, error) {
	row := q.db.QueryRow(ctx, getStateAtEvent,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.RecordID,
		arg.ID,
	)
	var i GetStateAtEventRow
	err := row.Scan(&i.StateAfter, &i.Revision, &i.Type)
	return i, err
}

const getStateAtRevision = `-- name: GetStateAtRevision :one
SELECT state_after, revision, type
FROM events
WHERE workspace_id = $1 AND collection_id = $2 AND record_id = $3 AND revision <= $4
ORDER BY seq DESC
LIMIT 1
`

type GetStateAtRevisionParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	RecordID     uuid.UUID `json:"record_id"`
	Revision     int64     `json:"revision"`
}

type GetStateAtRevisionRow struct {
	StateAfter []byte `json:"state_after"`
	Revision   int64  `json:"revision"`
	Type       string `json:"type"`
}

func (q *Queries) GetStateAtRevision(ctx context.Context, arg GetStateAtRevisionParams) (GetStateAtRevisionRow, error) {
	row := q.db.QueryRow(ctx, getStateAtRevision,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.RecordID,
		arg.Revision,
	)
	var i GetStateAtRevisionRow
	err := row.Scan(&i.StateAfter, &i.Revision, &i.Type)
	return i, err
}

const getStateAtTimestamp = `-- name: GetStateAtTimestamp :one
SELECT state_after, revision, type
FROM events
WHERE workspace_id = $1 AND collection_id = $2 AND record_id = $3 AND created_at <= $4
ORDER BY seq DESC
LIMIT 1
`

type GetStateAtTimestampParams struct {
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	CollectionID uuid.UUID          `json:"collection_id"`
	RecordID     uuid.UUID          `json:"record_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type GetStateAtTimestampRow struct {
	StateAfter []byte `json:"state_after"`
	Revision   int64  `json:"revision"`
	Type       string `json:"type"`
}

func (q *Queries) GetStateAtTimestamp(ctx context.Context, arg GetStateAtTimestampParams) (GetStateAtTimestampRow, error) {
	row := q.db.QueryRow(ctx, getStateAtTimestamp,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.RecordID,
		arg.CreatedAt,
	)
	var i GetStateAtTimestampRow
	err := row.Scan(&i.StateAfter, &i.Revision, &i.Type)
	return i, err
}

const listRecordEvents = `-- name: ListRecordEvents :many
SELECT revision, type, actor, state_after, created_at
FROM events
WHERE workspace_id = $1 AND collection_id = $2 AND record_id = $3
ORDER BY seq ASC
`

type ListRecordEventsParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	RecordID     uuid.UUID `json:"record_id"`
}

type ListRecordEventsRow struct {
	Revision   int64              `json:"revision"`
	Type       string             `json:"type"`
	Actor      pgtype.Text        `json:"actor"`
	StateAfter []byte             `json:"state_after"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRecordEvents(ctx context.Context, arg ListRecordEventsParams) ([]ListRecordEventsRow, error) {
	rows, err := q.db.Query(ctx, listRecordEvents, arg.WorkspaceID, arg.CollectionID, arg.RecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordEventsRow
	for rows.Next() {
		var i ListRecordEventsRow
		if err := rows.Scan(
			&i.Revision,
			&i.Type,
			&i.Actor,
			&i.StateAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
