// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Hash        []byte             `json:"hash"`
	Label       pgtype.Text        `json:"label"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type Collection struct {
	ID                  uuid.UUID          `json:"id"`
	WorkspaceID         uuid.UUID          `json:"workspace_id"`
	Name                string             `json:"name"`
	Level               string             `json:"level"`
	ActiveSchemaVersion pgtype.Int4        `json:"active_schema_version"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	Seq            int64              `json:"seq"`
	ID             uuid.UUID          `json:"id"`
	WorkspaceID    uuid.UUID          `json:"workspace_id"`
	CollectionID   uuid.UUID          `json:"collection_id"`
	RecordID       uuid.UUID          `json:"record_id"`
	Type           string             `json:"type"`
	Revision       int64              `json:"revision"`
	StateAfter     []byte             `json:"state_after"`
	Actor          pgtype.Text        `json:"actor"`
	Trace          []byte             `json:"trace"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Record struct {
	ID            uuid.UUID          `json:"id"`
	CollectionID  uuid.UUID          `json:"collection_id"`
	WorkspaceID   uuid.UUID          `json:"workspace_id"`
	SchemaVersion pgtype.Int4        `json:"schema_version"`
	Data          []byte             `json:"data"`
	Revision      int64              `json:"revision"`
	Status        string             `json:"status"`
	Actor         pgtype.Text        `json:"actor"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID         uuid.UUID          `json:"id"`
	Name       string             `json:"name"`
	PolicyMode string             `json:"policy_mode"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
