// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePolicy = `-- name: DeletePolicy :execrows
DELETE FROM policies WHERE id = $1 AND workspace_id = $2
`

type DeletePolicyParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeletePolicy(ctx context.Context, arg DeletePolicyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePolicy, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPolicy = `-- name: InsertPolicy :one
INSERT INTO policies (id, workspace_id, actor, collection_id, operation, effect)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, actor, collection_id, operation, effect, created_at
`

type InsertPolicyParams struct {
	ID           uuid.UUID   `json:"id"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	Actor        string      `json:"actor"`
	CollectionID pgtype.UUID `json:"collection_id"`
	Operation    string      `json:"operation"`
	Effect       string      `json:"effect"`
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, insertPolicy,
		arg.ID,
		arg.WorkspaceID,
		arg.Actor,
		arg.CollectionID,
		arg.Operation,
		arg.Effect,
	)
	var i Policy
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Actor,
		&i.CollectionID,
		&i.Operation,
		&i.Effect,
		&i.CreatedAt,
	)
	return i, err
}

const listPolicies = `-- name: ListPolicies :many
SELECT p.id, p.actor, p.collection_id, c.name AS collection_name, p.operation, p.effect, p.created_at
FROM policies p
LEFT JOIN collections c ON c.id = p.collection_id
WHERE p.workspace_id = $1
ORDER BY p.created_at ASC, p.id ASC
`

type ListPoliciesRow struct {
	ID             uuid.UUID          `json:"id"`
	Actor          string             `json:"actor"`
	CollectionID   pgtype.UUID        `json:"collection_id"`
	CollectionName pgtype.Text        `json:"collection_name"`
	Operation      string             `json:"operation"`
	Effect         string             `json:"effect"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListPolicies(ctx context.Context, workspaceID uuid.UUID) ([]ListPoliciesRow, error) {
	rows, err := q.db.Query(ctx, listPolicies, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesRow
	for rows.Next() {
		var i ListPoliciesRow
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.CollectionID,
			&i.CollectionName,
			&i.Operation,
			&i.Effect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesForRequest = `-- name: ListPoliciesForRequest :many
SELECT id, actor, collection_id, operation, effect
FROM policies
WHERE workspace_id = $1
  AND (collection_id = $2 OR collection_id IS NULL)
`

type ListPoliciesForRequestParams struct {
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	CollectionID pgtype.UUID `json:"collection_id"`
}

type ListPoliciesForRequestRow struct {
	ID           uuid.UUID   `json:"id"`
	Actor        string      `json:"actor"`
	CollectionID pgtype.UUID `json:"collection_id"`
	Operation    string      `json:"operation"`
	Effect       string      `json:"effect"`
}

func (q *Queries) ListPoliciesForRequest(ctx context.Context, arg ListPoliciesForRequestParams) ([]ListPoliciesForRequestRow, error) {
	rows, err := q.db.Query(ctx, listPoliciesForRequest, arg.WorkspaceID, arg.CollectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesForRequestRow
	for rows.Next() {
		var i ListPoliciesForRequestRow
		if err := rows.Scan(
			&i.ID,
			&i.Actor,
			&i.CollectionID,
			&i.Operation,
			&i.Effect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
