// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveRecord = `-- name: GetActiveRecord :one
SELECT id, collection_id, data, revision, status, actor
FROM records
WHERE workspace_id = $1 AND collection_id = $2 AND id = $3 AND status = 'active'
`

type GetActiveRecordParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	ID           uuid.UUID `json:"id"`
}

type GetActiveRecordRow struct {
	ID           uuid.UUID   `json:"id"`
	CollectionID uuid.UUID   `json:"collection_id"`
	Data         []byte      `json:"data"`
	Revision     int64       `json:"revision"`
	Status       string      `json:"status"`
	Actor        pgtype.Text `json:"actor"`
}

func (q *Queries) GetActiveRecord(ctx context.Context, arg GetActiveRecordParams) (GetActiveRecordRow, error) {
	row := q.db.QueryRow(ctx, getActiveRecord, arg.WorkspaceID, arg.CollectionID, arg.ID)
	var i GetActiveRecordRow
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Data,
		&i.Revision,
		&i.Status,
		&i.Actor,
	)
	return i, err
}

const getAnyRecordRevisionForUpdate = `-- name: GetAnyRecordRevisionForUpdate :one
SELECT revision
FROM records
WHERE workspace_id = $1 AND collection_id = $2 AND id = $3
FOR UPDATE
`

type GetAnyRecordRevisionForUpdateParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) GetAnyRecordRevisionForUpdate(ctx context.Context, arg GetAnyRecordRevisionForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getAnyRecordRevisionForUpdate, arg.WorkspaceID, arg.CollectionID, arg.ID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getRecordForUpdate = `-- name: GetRecordForUpdate :one
SELECT revision, data
FROM records
WHERE workspace_id = $1 AND collection_id = $2 AND id = $3 AND status = 'active'
FOR UPDATE
`

type GetRecordForUpdateParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	ID           uuid.UUID `json:"id"`
}

type GetRecordForUpdateRow struct {
	Revision int64  `json:"revision"`
	Data     []byte `json:"data"`
}

func (q *Queries) GetRecordForUpdate(ctx context.Context, arg GetRecordForUpdateParams) (GetRecordForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRecordForUpdate, arg.WorkspaceID, arg.CollectionID, arg.ID)
	var i GetRecordForUpdateRow
	err := row.Scan(&i.Revision, &i.Data)
	return i, err
}

const getRecordRevisionForUpdate = `-- name: GetRecordRevisionForUpdate :one
SELECT revision
FROM records
WHERE workspace_id = $1 AND collection_id = $2 AND id = $3 AND status = 'active'
FOR UPDATE
`

type GetRecordRevisionForUpdateParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) GetRecordRevisionForUpdate(ctx context.Context, arg GetRecordRevisionForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRecordRevisionForUpdate, arg.WorkspaceID, arg.CollectionID, arg.ID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const insertRecord = `-- name: InsertRecord :exec
INSERT INTO records (id, collection_id, workspace_id, data, revision, status, actor)
VALUES ($1, $2, $3, $4, $5, 'active', $6)
`

type InsertRecordParams struct {
	ID           uuid.UUID   `json:"id"`
	CollectionID uuid.UUID   `json:"collection_id"`
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	Data         []byte      `json:"data"`
	Revision     int64       `json:"revision"`
	Actor        pgtype.Text `json:"actor"`
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) error {
	_, err := q.db.Exec(ctx, insertRecord,
		arg.ID,
		arg.CollectionID,
		arg.WorkspaceID,
		arg.Data,
		arg.Revision,
		arg.Actor,
	)
	return err
}

const revertRecordData = `-- name: RevertRecordData :exec
UPDATE records SET data = $4, revision = $5, status = 'active', updated_at = now()
WHERE workspace_id = $1 AND collection_id = $2 AND id = $3
`

type RevertRecordDataParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	ID           uuid.UUID `json:"id"`
	Data         []byte    `json:"data"`
	Revision     int64     `json:"revision"`
}

func (q *Queries) RevertRecordData(ctx context.Context, arg RevertRecordDataParams) error {
	_, err := q.db.Exec(ctx, revertRecordData,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.ID,
		arg.Data,
		arg.Revision,
	)
	return err
}

const softDeleteRecord = `-- name: SoftDeleteRecord :exec
UPDATE records SET status = 'deleted', revision = $4, updated_at = now()
WHERE workspace_id = $1 AND collection_id = $2 AND id = $3
`

type SoftDeleteRecordParams struct {
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	CollectionID uuid.UUID `json:"collection_id"`
	ID           uuid.UUID `json:"id"`
	Revision     int64     `json:"revision"`
}

func (q *Queries) SoftDeleteRecord(ctx context.Context, arg SoftDeleteRecordParams) error {
	_, err := q.db.Exec(ctx, softDeleteRecord,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.ID,
		arg.Revision,
	)
	return err
}

const updateRecordData = `-- name: UpdateRecordData :exec
UPDATE records SET data = $4, revision = $5, actor = $6, updated_at = now()
WHERE workspace_id = $1 AND collection_id = $2 AND id = $3
`

type UpdateRecordDataParams struct {
	WorkspaceID  uuid.UUID   `json:"workspace_id"`
	CollectionID uuid.UUID   `json:"collection_id"`
	ID           uuid.UUID   `json:"id"`
	Data         []byte      `json:"data"`
	Revision     int64       `json:"revision"`
	Actor        pgtype.Text `json:"actor"`
}

func (q *Queries) UpdateRecordData(ctx context.Context, arg UpdateRecordDataParams) error {
	_, err := q.db.Exec(ctx, updateRecordData,
		arg.WorkspaceID,
		arg.CollectionID,
		arg.ID,
		arg.Data,
		arg.Revision,
		arg.Actor,
	)
	return err
}
