// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schemas.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveSchema = `-- name: GetActiveSchema :one
SELECT s.version, s.json_schema
FROM schemas s
JOIN collections c ON c.id = s.collection_id AND c.active_schema_version = s.version
WHERE c.id = $1
`

type GetActiveSchemaRow struct {
	Version    int32  `json:"version"`
	JsonSchema []byte `json:"json_schema"`
}

func (q *Queries) GetActiveSchema(ctx context.Context, id uuid.UUID) (GetActiveSchemaRow, error) {
	row := q.db.QueryRow(ctx, getActiveSchema, id)
	var i GetActiveSchemaRow
	err := row.Scan(&i.Version, &i.JsonSchema)
	return i, err
}

const getSchema = `-- name: GetSchema :one
SELECT id, collection_id, version, json_schema, lifecycle, indexed_fields, rationale, created_at, created_by
FROM schemas
WHERE collection_id = $1 AND version = $2
`

type GetSchemaParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	Version      int32     `json:"version"`
}

type GetSchemaRow struct {
	ID            uuid.UUID          `json:"id"`
	CollectionID  uuid.UUID          `json:"collection_id"`
	Version       int32              `json:"version"`
	JsonSchema    []byte             `json:"json_schema"`
	Lifecycle     string             `json:"lifecycle"`
	IndexedFields []byte             `json:"indexed_fields"`
	Rationale     pgtype.Text        `json:"rationale"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedBy     pgtype.Text        `json:"created_by"`
}

func (q *Queries) GetSchema(ctx context.Context, arg GetSchemaParams) (GetSchemaRow, error) {
	row := q.db.QueryRow(ctx, getSchema, arg.CollectionID, arg.Version)
	var i GetSchemaRow
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Version,
		&i.JsonSchema,
		&i.Lifecycle,
		&i.IndexedFields,
		&i.Rationale,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const insertSchema = `-- name: InsertSchema :one
INSERT INTO schemas (id, collection_id, workspace_id, version, json_schema, lifecycle, indexed_fields, rationale, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, collection_id, version, lifecycle, indexed_fields, created_at, created_by
`

type InsertSchemaParams struct {
	ID            uuid.UUID   `json:"id"`
	CollectionID  uuid.UUID   `json:"collection_id"`
	WorkspaceID   uuid.UUID   `json:"workspace_id"`
	Version       int32       `json:"version"`
	JsonSchema    []byte      `json:"json_schema"`
	Lifecycle     string      `json:"lifecycle"`
	IndexedFields []byte      `json:"indexed_fields"`
	Rationale     pgtype.Text `json:"rationale"`
	CreatedBy     pgtype.Text `json:"created_by"`
}

type InsertSchemaRow struct {
	ID            uuid.UUID          `json:"id"`
	CollectionID  uuid.UUID          `json:"collection_id"`
	Version       int32              `json:"version"`
	Lifecycle     string             `json:"lifecycle"`
	IndexedFields []byte             `json:"indexed_fields"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedBy     pgtype.Text        `json:"created_by"`
}

func (q *Queries) InsertSchema(ctx context.Context, arg InsertSchemaParams) (InsertSchemaRow, error) {
	row := q.db.QueryRow(ctx, insertSchema,
		arg.ID,
		arg.CollectionID,
		arg.WorkspaceID,
		arg.Version,
		arg.JsonSchema,
		arg.Lifecycle,
		arg.IndexedFields,
		arg.Rationale,
		arg.CreatedBy,
	)
	var i InsertSchemaRow
	err := row.Scan(
		&i.ID,
		&i.CollectionID,
		&i.Version,
		&i.Lifecycle,
		&i.IndexedFields,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listSchemas = `-- name: ListSchemas :many
SELECT version, lifecycle, indexed_fields, created_at, created_by
FROM schemas
WHERE collection_id = $1
ORDER BY version ASC
`

type ListSchemasRow struct {
	Version       int32              `json:"version"`
	Lifecycle     string             `json:"lifecycle"`
	IndexedFields []byte             `json:"indexed_fields"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CreatedBy     pgtype.Text        `json:"created_by"`
}

func (q *Queries) ListSchemas(ctx context.Context, collectionID uuid.UUID) ([]ListSchemasRow, error) {
	rows, err := q.db.Query(ctx, listSchemas, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchemasRow
	for rows.Next() {
		var i ListSchemasRow
		if err := rows.Scan(
			&i.Version,
			&i.Lifecycle,
			&i.IndexedFields,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCollection = `-- name: LockCollection :one
SELECT id, level, active_schema_version
FROM collections
WHERE id = $1
FOR UPDATE
`

type LockCollectionRow struct {
	ID                  uuid.UUID   `json:"id"`
	Level               string      `json:"level"`
	ActiveSchemaVersion pgtype.Int4 `json:"active_schema_version"`
}

func (q *Queries) LockCollection(ctx context.Context, id uuid.UUID) (LockCollectionRow, error) {
	row := q.db.QueryRow(ctx, lockCollection, id)
	var i LockCollectionRow
	err := row.Scan(&i.ID, &i.Level, &i.ActiveSchemaVersion)
	return i, err
}

const nextSchemaVersion = `-- name: NextSchemaVersion :one
SELECT COALESCE(MAX(version), 0) + 1 AS next
FROM schemas
WHERE collection_id = $1
`

func (q *Queries) NextSchemaVersion(ctx context.Context, collectionID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextSchemaVersion, collectionID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const setCollectionActiveVersion = `-- name: SetCollectionActiveVersion :exec
UPDATE collections SET active_schema_version = $2, level = 'typed', updated_at = now()
WHERE id = $1
`

type SetCollectionActiveVersionParams struct {
	ID                  uuid.UUID   `json:"id"`
	ActiveSchemaVersion pgtype.Int4 `json:"active_schema_version"`
}

func (q *Queries) SetCollectionActiveVersion(ctx context.Context, arg SetCollectionActiveVersionParams) error {
	_, err := q.db.Exec(ctx, setCollectionActiveVersion, arg.ID, arg.ActiveSchemaVersion)
	return err
}

const setSchemaLifecycle = `-- name: SetSchemaLifecycle :exec
UPDATE schemas SET lifecycle = $3
WHERE collection_id = $1 AND version = $2
`

type SetSchemaLifecycleParams struct {
	CollectionID uuid.UUID `json:"collection_id"`
	Version      int32     `json:"version"`
	Lifecycle    string    `json:"lifecycle"`
}

func (q *Queries) SetSchemaLifecycle(ctx context.Context, arg SetSchemaLifecycleParams) error {
	_, err := q.db.Exec(ctx, setSchemaLifecycle, arg.CollectionID, arg.Version, arg.Lifecycle)
	return err
}
