// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (id, name, policy_mode)
VALUES ($1, $2, $3)
RETURNING id, name, policy_mode, created_at
`

type CreateWorkspaceParams struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	PolicyMode string    `json:"policy_mode"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, arg.ID, arg.Name, arg.PolicyMode)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PolicyMode,
		&i.CreatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, name, policy_mode, created_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PolicyMode,
		&i.CreatedAt,
	)
	return i, err
}
